[General]
loglevel = notify
bypass-system = true
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,localhost,*.local,e.crashlytics.com,captive.apple.com,::ffff:0:0:0:0/1,::ffff:128:0:0:0/1
# DNS设置或根据自己网络情况进行相应设置
bypass-tun = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
dns-server = 119.29.29.29,223.5.5.5
allow-wifi-access = false

[Proxy]
DIRECT = direct

[Proxy Group]
✈️ 机场专线 = select, policy-path=your.surge.list.here, update-interval=0, DIRECT, no-alert=0, hidden=0
🤖 谷歌分析 = select, policy-path=your.surge.list.here, update-interval=0, DIRECT, no-alert=0, hidden=0
📲 社交媒体 = select, policy-path=your.surge.list.here, update-interval=0, DIRECT, no-alert=0, hidden=0
🍎 苹果服务 = select, policy-path=your.surge.list.here, update-interval=0, DIRECT, no-alert=0, hidden=0
Ⓜ️ 微软服务 = select, policy-path=your.surge.list.here, update-interval=0, DIRECT, no-alert=0, hidden=0
🇸🇬 Netflix = select, policy-path=your.surge.list.here, update-interval=0, DIRECT, no-alert=0, hidden=0
🎥 其他国外流媒体 = select,policy-path=your.surge.list.here, update-interval=0, DIRECT, no-alert=0, hidden=0
🛑 广告拦截 = select, REJECT, no-alert=0, hidden=0
🐟 final = select, policy-path=your.surge.list.here, update-interval=0, DIRECT

[Rule]
RULE-SET,https://raw.githubusercontent.com/limbopro/Profiles/master/limbopro/Googleanalytics.list,🤖 谷歌分析
RULE-SET,https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adblock4limbo.list,🛑 广告拦截
RULE-SET,https://raw.githubusercontent.com/limbopro/Script/master/Surge/AdRule.list,🛑 广告拦截
RULE-SET,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Advertising.list,🛑 广告拦截
RULE-SET,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Hijacking.list,🛑 广告拦截
RULE-SET,https://raw.githubusercontent.com/limbopro/Profiles4limbo/main/airports.list,✈️ 机场专线
RULE-SET,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/Video/Netflix.list,🇸🇬 Netflix
RULE-SET,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/Streaming.list,🎥 其他国外流媒体
RULE-SET,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Global.list,📲 社交媒体
RULE-SET,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/Apple/Apple.list,🍎 苹果服务
RULE-SET,https://raw.githubusercontent.com/limbopro/Profiles/master/limbopro/Microsoft.list,Ⓜ️ 微软服务
RULE-SET,https://raw.githubusercontent.com/NobyDa/Script/master/Surge/Download.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/limbopro/Profiles/master/limbopro/Local.list,DIRECT
FINAL,🐟 final

[URL Rewrite]

[MITM]

[Script]